# ==============================================================================
# COMPREHENSIVE TIERED ANALYTICS SUITE - CONDA ENVIRONMENT
# ==============================================================================
# Author: Brandon Deloatch
# Affiliation: Quipu Research Labs, LLC
# Date: 2025-10-02
# Version: v1.3
# ==============================================================================

name: analytics-suite

channels:
  - conda-forge
  - defaults
  - plotly
  - pyviz

dependencies:
  # Python Runtime
  - python>=3.8

  # Core Data Science Stack
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - statsmodels>=0.14.0

  # Machine Learning
  - scikit-learn>=1.3.0
  - xgboost>=1.7.0
  - lightgbm>=4.0.0

  # Visualization
  - plotly>=5.15.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Jupyter Environment
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0

  # Specialized Analytics
  - pywavelets>=1.4.0

  # Development Tools
  - black>=23.0.0
  - flake8>=6.0.0

  # Performance
  - numba>=0.57.0
  - tqdm>=4.65.0

  # pip dependencies (not available via conda)
  - pip
  - pip:
    - catboost>=1.2.0
    - diptest>=0.6.0
    - pykalman>=0.9.5
    - ta>=0.10.0
    - tensorflow>=2.13.0

# ==============================================================================
# USAGE INSTRUCTIONS
# ==============================================================================
#
# Create Environment:
#   conda env create -f environment.yml
#
# Activate Environment:
#   conda activate analytics-suite
#
# Update Environment:
#   conda env update -f environment.yml --prune
#
# Export Current Environment:
#   conda env export > environment.yml
#
# Remove Environment:
#   conda env remove -n analytics-suite
#
# ==============================================================================
# PLATFORM-SPECIFIC NOTES
# ==============================================================================
#
# Apple Silicon (M1/M2):
#   - TensorFlow will use Apple's Metal Performance Shaders
#   - Some packages may need to be installed via pip in the activated environment
#
# Windows:
#   - Visual C++ redistributables may be required for some packages
#   - Consider using conda-forge channel for better Windows compatibility
#
# Linux:
#   - Most packages available through conda-forge
#   - CUDA support available for GPU acceleration
#
# ==============================================================================